# Cache gems in between builds
cache:
  paths:
  - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v
  #- gem install bundler --no-ri --no-rdoc
  - echo "Yes"
  - bundle install -j4 --path vendor
  - echo "On my way"

stages:
  - lint
  - build

rubocop:
  stage: lint
  script:
  - rubocop
  tags:
  - ruby

gem:
  stage: build
  script:
  - rake build
  tags:
  - ruby