AllCops:
  DisplayCopNames: true

Style/NumericLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
